# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages
latex: false
fortran: false
warnings_are_errors: false

jobs:
  include:
  - r: devel
  - os: osx
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  # - r: release
  #   env:
  #     - DEVEL_PACKAGES=true
  #   r_github_packages:
  #     - RcppCore/Rcpp
  #     - r-lib/rlang
  #     - tidyverse/tibble
  #     - tidyverse/tidyselect

matrix:
  fast_finish: true
  # allow_failures:
  # - env: DEVEL_PACKAGES=true

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_SYSTEM_CLOCK_=FALSE
